services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: easydocs
      POSTGRES_PASSWORD: easydocs123
      POSTGRES_DB: easydocs_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: always
    env_file:
      - backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code
    environment:
      - DATABASE_URL=postgresql://easydocs:easydocs123@db:5432/easydocs_db
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=1440
    depends_on:
      - db

volumes:
  postgres_data: