"""add mandatory events and notifications

Revision ID: 084066dd81e2
Revises: 77f1e3eefdaa
Create Date: 2026-08-03 14:39:39.971884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '084066dd81e2'
down_revision: Union[str, Sequence[str], None] = '77f1e3eefdaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('institution_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('calendar_event_id', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['calendar_event_id'], ['calendar_events.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('calendar_events', sa.Column('is_mandatory', sa.Boolean(), nullable=False))
    op.add_column('calendar_events', sa.Column('reminder_days_before', sa.Integer(), nullable=True))
    op.add_column('calendar_events', sa.Column('source_event_id', sa.String(), nullable=True))
    op.add_column('calendar_events', sa.Column('reminder_sent', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'calendar_events', 'calendar_events', ['source_event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'calendar_events', type_='foreignkey')
    op.drop_column('calendar_events', 'reminder_sent')
    op.drop_column('calendar_events', 'source_event_id')
    op.drop_column('calendar_events', 'reminder_days_before')
    op.drop_column('calendar_events', 'is_mandatory')
    op.drop_table('notifications')
    # ### end Alembic commands ###
