"""calendar institution nullable

Revision ID: 972e966dbdac
Revises: 4a6e1e33621f
Create Date: 2026-07-18 20:25:23.565347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '972e966dbdac'
down_revision: Union[str, Sequence[str], None] = '4a6e1e33621f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calendar_events', 'institution_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calendar_events', 'institution_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
