"""crear tablas documents

Revision ID: d0823b2c17dc
Revises: 31628ccb7d7b
Create Date: 2026-06-06 15:32:56.490019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0823b2c17dc'
down_revision: Union[str, Sequence[str], None] = '31628ccb7d7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_type', sa.Enum('LR001', 'LR002', 'LR003', 'LR004', 'LR005', 'LR006', 'LR007', 'LR008', 'LR009', 'certificado_aptitud_laboral', 'certificado_aptitud_salud', 'certificado_conocimientos', 'constancia_asistencia', 'constancia_estudio', name='documenttype'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('template_html', sa.String(), nullable=False),
    sa.Column('required_fields', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_type')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('institution_id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'ai_draft', 'generated', 'cancelled', name='documentstatus'), nullable=False),
    sa.Column('document_data', sa.JSON(), nullable=False),
    sa.Column('pdf_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['document_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    op.drop_table('document_templates')
    # ### end Alembic commands ###
