"""add logo_url to institutions

Revision ID: dccca96042e6
Revises: 3db356717b5d
Create Date: 2026-06-17 16:20:08.994952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dccca96042e6'
down_revision: Union[str, Sequence[str], None] = '3db356717b5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrollments')
    op.drop_table('students')
    op.drop_table('programs')
    op.add_column('institutions', sa.Column('logo_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('institutions', 'logo_url')
    op.create_table('programs',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('institution_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('resolution', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('total_hours', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('certificate_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('programs_institution_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('programs_pkey'))
    )
    op.create_table('students',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('institution_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('document_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('document_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('document_place', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('neighborhood', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('commune', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_minor', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('guardian_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('guardian_document', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('guardian_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('guardian_phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('students_institution_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('students_pkey'))
    )
    op.create_table('enrollments',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('institution_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('program_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('enrollment_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('folio', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('certificate_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('year', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('enrollments_institution_id_fkey')),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], name=op.f('enrollments_program_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('enrollments_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('enrollments_pkey'))
    )
    # ### end Alembic commands ###
